spring.datasource.url=jdbc:postgresql://localhost:5432/watchlisttracker
spring.datasource.username=postgres
spring.datasource.password=lalitgera

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

spring.task.scheduling.pool.size=2
