spring.application.name=watchlist-service
spring.datasource.url=jdbc:postgresql://localhost:5432/databaseName
spring.datasource.username=root
spring.datasource.password=pass
# Ensure correct spelling of 'postgresql' in the URL

